/* SPDX-License-Identifier: MPL-2.0 */

#define STREAMLIKE_TEST_NAME(name) \
	STREAMLIKE_TEST_NAME1(STREAMLIKE_PREFIX, name)
#define STREAMLIKE_TEST_NAME1(prefix, name) STREAMLIKE_TEST_NAME2(prefix, name)
#define STREAMLIKE_TEST_NAME2(prefix, name) prefix##name
#define STREAMLIKE_FN_TEST(name) STREAMLIKE_FN_TEST1(STREAMLIKE_TEST_NAME(name))
#define STREAMLIKE_FN_TEST1(name) FN_TEST(name)

STREAMLIKE_FN_TEST(short_peek_short_reads)
{
	STREAMLIKE_FDS();
	int msg_flags = 0;
	char buf[PAYLOAD_LEN] = {};

	STREAMLIKE_CONNECT();

	STREAMLIKE_SEND(0, PAYLOAD_LEN);
	STREAMLIKE_WAIT_READABLE();
	STREAMLIKE_PEEK(0, SHORT_LEN);
	STREAMLIKE_RECV(0, SHORT_LEN);
	STREAMLIKE_RECV(SHORT_LEN, PAYLOAD_LEN - SHORT_LEN);
	STREAMLIKE_CLOSE();
}
END_TEST()

STREAMLIKE_FN_TEST(short_peek_full_read)
{
	STREAMLIKE_FDS();
	int msg_flags = 0;
	char buf[PAYLOAD_LEN] = {};

	STREAMLIKE_CONNECT();

	STREAMLIKE_SEND(0, PAYLOAD_LEN);
	STREAMLIKE_WAIT_READABLE();
	STREAMLIKE_PEEK(0, SHORT_LEN);
	STREAMLIKE_RECV(0, PAYLOAD_LEN);
	STREAMLIKE_CLOSE();
}
END_TEST()

STREAMLIKE_FN_TEST(append_after_peek_short_reads)
{
	STREAMLIKE_FDS();
	int msg_flags = 0;
	char buf[PAYLOAD_LEN] = {};

	STREAMLIKE_CONNECT();

	STREAMLIKE_SEND(0, SHORT_LEN);
	STREAMLIKE_WAIT_READABLE();
	STREAMLIKE_PEEK(0, SHORT_LEN);
	STREAMLIKE_SEND(SHORT_LEN, PAYLOAD_LEN - SHORT_LEN);
	STREAMLIKE_WAIT_APPENDED_READABLE();
	STREAMLIKE_RECV(0, SHORT_LEN);
	STREAMLIKE_RECV(SHORT_LEN, PAYLOAD_LEN - SHORT_LEN);
	STREAMLIKE_CLOSE();
}
END_TEST()

STREAMLIKE_FN_TEST(append_after_peek_full_read)
{
	STREAMLIKE_FDS();
	int msg_flags = 0;
	char buf[PAYLOAD_LEN] = {};

	STREAMLIKE_CONNECT();

	STREAMLIKE_SEND(0, SHORT_LEN);
	STREAMLIKE_WAIT_READABLE();
	STREAMLIKE_PEEK(0, SHORT_LEN);
	STREAMLIKE_SEND(SHORT_LEN, PAYLOAD_LEN - SHORT_LEN);
	STREAMLIKE_WAIT_APPENDED_READABLE();
	STREAMLIKE_RECV(0, PAYLOAD_LEN);
	STREAMLIKE_CLOSE();
}
END_TEST()

STREAMLIKE_FN_TEST(full_peek_short_reads)
{
	STREAMLIKE_FDS();
	int msg_flags = 0;
	char buf[PAYLOAD_LEN] = {};

	STREAMLIKE_CONNECT();

	STREAMLIKE_SEND(0, PAYLOAD_LEN);
	STREAMLIKE_WAIT_READABLE();
	STREAMLIKE_PEEK(0, PAYLOAD_LEN);
	STREAMLIKE_RECV(0, SHORT_LEN);
	STREAMLIKE_RECV(SHORT_LEN, PAYLOAD_LEN - SHORT_LEN);
	STREAMLIKE_CLOSE();
}
END_TEST()

#undef STREAMLIKE_TEST_NAME
#undef STREAMLIKE_TEST_NAME1
#undef STREAMLIKE_TEST_NAME2
#undef STREAMLIKE_FN_TEST
#undef STREAMLIKE_FN_TEST1
