name: Test Kata Guest OS

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare-kata-runtime-host:
    runs-on: ubuntu-latest
    container:
      image: asterinas/asterinas:0.17.1-20260319
      options: --privileged --cgroupns host
    env:
      KATA_CGROUP_NAMESPACE: host
    defaults:
      run:
        shell: bash
    timeout-minutes: 90
    steps:
      - name: Check disk space
        run: |
          set -euxo pipefail
          df -h

      - uses: actions/checkout@v4

      - name: Install Kata environment
        run: |
          set -euxo pipefail
          bash tools/kata/kata_env.sh install

      - name: Run Kata pass 1
        run: |
          set -euxo pipefail
          bash tools/kata/run_kata.sh pass

      - name: Run Kata pass 2
        run: |
          set -euxo pipefail
          bash tools/kata/run_kata.sh pass
