name: Update Online API Docs

on:
  # The scheduled job for nightly API docs
  schedule:
    - cron: "* * * * *"
  # The job for API docs for each new version
  push:
    branches:
      - main
    paths:
      - VERSION

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: asterinas/asterinas:0.4.2

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'asterinas/asterinas'
          path: 'asterinas'

      - name: Build & Upload nightly API docs
        if: github.event_name == 'schedule'
        env:
          API_DOCS_NIGHTLY_PUBLISH_KEY: ${{ secrets.API_DOCS_NIGHTLY_PUBLISH_KEY }}
        run: |
          cd asterinas
          make install_osdk
          cd framework/aster-frame
          cargo osdk doc
          cd ../../..
          echo "$API_DOCS_NIGHTLY_PUBLISH_KEY\n" > ./api_docs_nightly_publish_key
          chmod 600 ./api_docs_nightly_publish_key
          ssh-keygen -y -f ./api_docs_nightly_publish_key > /dev/null
          ssh-keyscan -t rsa github.com >> ./known_hosts
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          GIT_SSH_COMMAND="ssh -i ./api_docs_nightly_publish_key -o UserKnownHostsFile=./known_hosts" git clone git@github.com:asterinas/api-docs-nightly.git nightly_api_docs
          cd nightly_api_docs
          git checkout --orphan new_branch
          git rm -rf *
          cp -r ../asterinas/target/x86_64-unknown-none/doc/* ./
          git add .
          git commit -am "Update nightly API docs"
          git branch -D main
          git branch -m main
          GIT_SSH_COMMAND="ssh -i ../api_docs_nightly_publish_key -o UserKnownHostsFile=../known_hosts" git push -f origin main